apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  annotations:
    # class annotation only needed if cert-controller-manager is started with --cert-class=myclass
    #cert.gardener.cloud/class: myclass
  name: cert-ca
  namespace: default
spec:
  commonName: cert1.mydomain.com
  dnsNames:
  - cert1.my-other-domain.com
  # if issuer is not specified, the default issuer is used
  issuerRef:
    name: issuer-ca
  # optionally specify secret to store certificate
  secretRef:
    name: cert-ca-secret
    namespace: default
